spring:
  application:
    name: doc-analyzer-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        options:
          model: gemini-1.5-flash
          temperature: 0.1

server:
  port: 8080