spring:
  application:
    name: doc-analyzer-backend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

gemini:
  api-key: ${GEMINI_API_KEY}

server:
  port: 12100
  servlet:
    context-path: /api/v1/document-generator